package game

type GameActionType int

const (
	GAME_ACTION_ERROR GameActionType = iota
	GAME_ACTION_END_OF_GAME

	GAME_ACTION_DEAL
	GAME_ACTION_BID
	GAME_ACTION_PLAY_CARD
	GAME_ACTION_ANNOUNCE_TWENTY
	GAME_ACTION_ANNOUNCE_FIFTY
	GAME_ACTION_ANNOUNCE_BELLA
	GAME_ACTION_ANNOUNCE_TRUMP
	GAME_ACTION_ANNOUNCE_TRICK_WINNER
	GAME_ACTION_ANNOUNCE_LAST_TRICK_WINNER
	GAME_ACTION_CHOOSE_DEALER
	GAME_ACTION_CUT_DECK
)
