package game

type GameEventType int

const (
	GAME_EVENT_ERROR GameEventType = iota
	GAME_EVENT_END_OF_GAME

	GAME_EVENT_DEAL
	GAME_EVENT_BID
	GAME_EVENT_PLAY_CARD
	GAME_EVENT_ANNOUNCE_TWENTY
	GAME_EVENT_ANNOUNCE_FIFTY
	GAME_EVENT_ANNOUNCE_BELLA
	GAME_EVENT_ANNOUNCE_TRUMP
	GAME_EVENT_ANNOUNCE_TRICK_WINNER
	GAME_EVENT_ANNOUNCE_LAST_TRICK_WINNER
	GAME_EVENT_CHOOSE_DEALER
	GAME_EVENT_CUT_DECK
)
